---
- name: set host to ip Mappingin /etc/hosts file of all the instance
  hosts: all
  task:
    - name: import vpc setup variable
      include_vars: group_vars/hostsip

- name: update hosts file for all the hosts
  blockinfile: 
    path: /etc/hosts
    block: |
      {{web01_ip}} web01
      {{app01_ip}} app01
      {{rmq01_ip}} rmq01
      {{mc01_ip}} mc01
      {{db01_ip}} db01

