---
  - name: build artifact ROOT.war & SQL file to be copied in the files/dir
    import_playbook: build.yml

  - name: Set Hosts to IP Mapping in /etc/hosts file of all servers
    import_playbook: set_host_in_map.yml

  - name: Setup dbserver
    import_playbook: db.yml

  - name: Deploy SQL file on dbserver
    import_playbook: dbdeploy.yml

  - name: Setup Memcached service
    import_playbook: memcached.yml

  - name: Setup rabbitmq service
    import_playbook: rabbitmq.yml

  - name: Setup Tomcat application server
    import_playbook: appserver.yml

  - name: Setup Nginx webserver
    import_playbook: web.yml
